#Training data generation of SEIPQR model with Multiplicative Environmental Noise COVID eigenvalue regime

#Edited from published codes by Bury et al. (2021), Deep learning for early warning signals of tipping points, PNAS. 
#python libraries
#
# Chakraborty et al. (2024), An early warning indicator trained on stochastic disease-spreading models with different noises
# https://zenodo.org/records/12537663
# 
# 
#  modified by Maya Rangarajan
#  1. Extended SIR to SEIPR
#  2. Extract null from each transcritical run
#  3. Parallelized simulations
#
#
#  INSTRUCTIONS:
#  This code generates both null and transcritical synthetic data in one run
#  Null data is generated by truncating the last 28 days of transcritical window
#  Noise regime -- Additive White
#  Before running, set the following variables: count, numSims, block_size, null_offset, LOW_FREQ_POWER, HIGH_NOISE, NUM_THREADS
#  all simulations saved in folder training_data in parent to pwd


import warnings
from urllib3.exceptions import NotOpenSSLWarning
warnings.simplefilter("ignore", NotOpenSSLWarning)
warnings.filterwarnings("ignore", category=NotOpenSSLWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

import numpy as np 
import pandas as pd 
import matplotlib as mlp 
import matplotlib.pyplot as plt 
import os 
import ewstools 
import random
import sys
from tqdm import trange
from tqdm import tqdm
import gc
from concurrent.futures import ThreadPoolExecutor, as_completed
from functools import partial
from joblib import Parallel, delayed


#  ============ SET THESE VARIABLES BEFORE RUN  =================
count = 3 # batch number for directory
sim_index = 25000 # starting index number is sim_index + 1
numSims = 25000    # number of null/transcritical simulations
block_size = 2500 # number of simulation runs per setting of pi and phi
null_offset = 50000 # null index number is TC index number + null_offset
LOW_FREQ_POWER = True
HIGH_NOISE = False # run 10% of additive noise runs at higher noise level
NUM_THREADS = 12  # adjust to available CPU cores

global_seed = 123456 + count * 111111
master_rng = np.random.default_rng(global_seed)

phase1_seeds = master_rng.integers(
    low=0,
    high=2**63,
    size=numSims,
    dtype=np.int64
)

#parameters
dt = 0.01
t0 = 0
tmax = 1500
tburn = 200                                           

# segment lengths
tphase_1 = 1500
tramp_1 = 1410 #duration of beta ramp, rest of tramp_1 is intervention ramp
tramp_pi = 30
tflat_pi = 60
nphase_1 = int(tphase_1/ dt)
nramp_1 = int(tramp_1 / dt)

t = np.arange(t0,tphase_1,dt)
t_1 = np.arange(t0,tramp_1,dt)  

I = np.zeros(len(t))

#arrays to store single time-series data

t_pi = t[(t > tramp_1) & (t<=tramp_1 + tramp_pi)] 
t_flat = t[t > tramp_1 + tramp_pi]
pi = np.zeros(len(t))
phi = np.zeros(len(t))
beta = np.zeros(len(t))

pi_ramp_mask = (t > tramp_1) & (t <= tramp_1 + tramp_pi)
pi_flat_mask = t > tramp_1 + tramp_pi

tphase_2 = 1500
nphase_2 = int(tphase_2/ dt)

dt2 = 1                                      
rw = 0.25                                    
span=0.2 if not LOW_FREQ_POWER else 0.35                                                                   
ews = ['var','ac']


# Model
def de_fun_S(S,I,P,Q,Lambda, beta,pi, phi,epsilon_q,mu):
  return Lambda-mu*S-beta*S*I-pi*S+phi*P-beta*(1- epsilon_q)*S*Q

def de_fun_E(S,E,I,P,Q, beta,theta, epsilon, epsilon_q, mu):
  return beta*S*I-(mu+theta)*E+(1-epsilon)*beta*P*I+(1-epsilon_q)*beta*S*Q

def de_fun_I(E,I,theta,gamma,delta, mu):
  return theta*E-(mu+gamma+delta)*I

def de_fun_P(S,I,P,beta,pi,phi,epsilon,mu):
   return pi*S-(mu+phi)*P-(1-epsilon)*beta*P*I

def de_fun_Q(Q, I, delta, mu, tau):
    return delta*I - (mu+tau)*Q

def de_fun_R(I,R,Q,gamma,tau,mu):
  return gamma*I+tau*Q-mu*R

def save_csv(i, groups, count, sim_index):
    sid = sim_index + i
    
    # -------- I time series --------
    df_I = groups[(i, "I")]

    df_I[["Time", "state"]].rename(
        columns={"state": "I"}
    ).to_csv(
        f"../training_data/AddNoise/output_sims_batch{count}/tseries{sid}.csv",
        index=False
    )

    # -------- residuals --------
    df_I[["Time", "residuals"]].to_csv(
        f"../training_data/AddNoise/resids{count}/resids{sid}.csv",
        index=False
    ) 
def save_null_csv(i, groups, count, null_offset):
    sid = null_offset + i + sim_index
    df_I = groups[(i, "I")]
    df_I[["Time", "state"]].rename(columns={"state": "I"}).to_csv(
        f"../training_data/AddNoise/output_sims_batch{count}/tseries{sid}.csv", index=False
    )
    df_I[["Time", "residuals"]].to_csv(
        f"../training_data/AddNoise/resids{count}/resids{sid}.csv", index=False
    )


def process_sim(i, df_traj_filt, tbif, span, rw):
    """
    Compute EWS for one simulation i (both S and I).
    Returns a single concatenated DataFrame for this sim.
    """
    dfs = []
    for var in ['I']:
        ews_dic = ewstools.core.TimeSeries(df_traj_filt.loc[i+1][var], 
                                          transition=tbif[i])
      
        ews_dic.detrend(method='Lowess', span=span)                                
        ews_dic.compute_auto(rolling_window=rw, lag=1)                             
        ews_dic.compute_var(rolling_window=rw)                                     

        # The DataFrame of EWS
        z1 = ews_dic.state                                                         
        z2 = ews_dic.ews                                                           
        df_ews_temp = pd.concat([z1, z2], axis=1)
    
        df_ews_temp['tsid'] = i+1
        df_ews_temp['Variable'] = var
        dfs.append(df_ews_temp)
    
    return pd.concat(dfs)  # single DataFrame per simulation

def process_null_sim(i, df_traj_filt, tbif, span, rw):
    dfs = []
    for var in ['I']:
        ts_full = df_traj_filt.loc[i+1][var]
        cutoff = tbif[i] - 28
        ts_trunc = ts_full[ts_full.index <= cutoff] if cutoff > ts_full.index.min() else ts_full
        ews_dic = ewstools.core.TimeSeries(ts_trunc, transition=None)
        ews_dic.detrend(method='Lowess', span=span)
        ews_dic.compute_auto(rolling_window=rw, lag=1)
        ews_dic.compute_var(rolling_window=rw)
        df_ews_temp = pd.concat([ews_dic.state, ews_dic.ews], axis=1)
        df_ews_temp['tsid'] = i+1
        df_ews_temp['Variable'] = var
        dfs.append(df_ews_temp)
    return pd.concat(dfs)

#model parameters
Lambda = 100                                     
S0_init = 500                                   
I0_init = 2
E0_init = 2
P0_init = 1
Q0_init = 1
R0_init = 2
mu = 0.75
theta= 10
gamma = 5 
# source: https://www.nature.com/articles/s41591-020-0869-5

epsilon = 0.6
epsilon_q = 0.85

delta = master_rng.uniform(0.1,0.3) # was (0.1,0.3)
tau = master_rng.uniform(0.048,0.071)

num_blocks = int(np.ceil(numSims / block_size))

# Behavioral timescale range (days)
tau_SP_min = 3.0 if not LOW_FREQ_POWER else 6.0
tau_SP_max = 15.0

# Protected fraction range
p_star_min = 0.2
p_star_max = 0.6

log_tau_SP_blocks = master_rng.uniform(
    np.log(tau_SP_min),
    np.log(tau_SP_max),
    size=num_blocks
)
tau_SP_blocks = np.exp(log_tau_SP_blocks)

p_star_blocks = master_rng.uniform(
    p_star_min,
    p_star_max,
    size=num_blocks
)

# Convert to rates per block
pi_blocks  = p_star_blocks / tau_SP_blocks
phi_blocks = (1.0 - p_star_blocks) / tau_SP_blocks

# Expand to per-simulation arrays
param_pi  = np.repeat(pi_blocks,  block_size)[:numSims]
param_phi = np.repeat(phi_blocks, block_size)[:numSims]

# Final (post-intervention) values
param_pi_final  = 0.2 * param_pi
param_phi_final = param_phi

# set Ro target at end of phase 1 and set beta target appropriately
Ro_target = master_rng.uniform(0.3, 0.95, size=numSims)
K = (
    theta * (Lambda / mu) *
    (mu + param_phi + (1 - epsilon) * param_pi) /
    (
        (mu + gamma) *
        (mu + theta) *
        (mu + param_phi + param_pi)
    )
)
# bifurcation point added for debugging
betabif = mu*(mu+theta)*(mu+gamma)/(theta*Lambda)      # increased to tip it slightly over               
# print('betabif=', betabif)

# ensure total matches t length
assert tramp_1 + tramp_pi + tflat_pi <= tphase_1

# ================== PHASE 1 = infection ramp + intervention ramp + intervention steady state
print('Setting params for Phase I \n')

# ======== model beta =======================
beta_intercept = []
beta_slope = []
beta_target = []

right_intercept = betabif / 2 
mid_intercept = right_intercept / 2 

beta_intercept = master_rng.triangular(0, mid_intercept, right_intercept, size=numSims)
# beta_target = master_rng.uniform(1.02, 1.07,size=numSims) * betabif

# Phase 1 beta target chosen to hit desired Ro at end of Phase 1
beta_target = Ro_target / K

# Optional safety clamp (prevents absurd values if params are extreme)
beta_target = np.clip(beta_target, 1e-6, None)


beta_slope = (beta_target - beta_intercept) / tramp_1

# ================= PHASE 1 model pi  ===================
# phi is constant
pi_slope = []

pi_slope = param_pi / tramp_pi

 # Initialise a list to collect trajectories
                                     
tbif = np.zeros(numSims) 
betas = []

# save last value of each sim for phase 2
S_last = []
E_last = []
I_last = []
P_last = []
Q_last = []
R_last = []
beta_last = []
pi_last = []
phi_last = []

# Pre-allocate arrays to store exit values of phase 1
S_final = np.zeros(numSims)
E_final = np.zeros(numSims)
I_final = np.zeros(numSims)
P_final = np.zeros(numSims)
Q_final = np.zeros(numSims)
R_final = np.zeros(numSims)
beta_final = np.zeros(numSims)
pi_final = np.zeros(numSims)
phi_final = np.zeros(numSims)

# loop over simulations
print('\nBegin simulations Phase I \n')
def run_one_sim(j):

    import warnings
    from urllib3.exceptions import NotOpenSSLWarning
    warnings.filterwarnings("ignore", category=NotOpenSSLWarning)

    rng = np.random.default_rng(phase1_seeds[j])

    Ro = np.zeros(len(t), dtype=float)


    S0 = S0_init                                   
    I0 = I0_init
    E0 = E0_init
    P0 = P0_init
    Q0 = Q0_init
    R0 = R0_init
    S_burn, E_burn, I_burn, P_burn, Q_burn, R_burn = S0, E0, I0, P0, Q0, R0

    # noise intensity
    sigma_S = rng.triangular(0, 0.02, 0.25)                                    
    sigma_I = rng.triangular(0, 0.02, 0.25)      
    sigma_E = rng.triangular(0, 0.02, 0.25)      
    sigma_P = rng.triangular(0, 0.02, 0.25) 
    sigma_Q = rng.triangular(0, 0.02, 0.25)       
    sigma_R = rng.triangular(0, 0.02, 0.25)  

    
    # ---------- beta ----------
    beta = np.zeros(len(t))
    beta[:len(t_1)] = beta_intercept[j] + beta_slope[j] * t_1
    beta[len(t_1):] = beta[len(t_1) - 1]

    # ---------- pi / phi ----------
    pi = np.zeros(len(t))
    phi = np.zeros(len(t))

    pi[pi_ramp_mask] = pi_slope[j] * (t[pi_ramp_mask] - tramp_1)
    pi[pi_flat_mask] = pi_slope[j] * tramp_pi
    phi[:] = param_phi[j]  
    
    # ---------- noise ----------
    sqrt_dt = np.sqrt(dt)

    dW_S_burn = rng.normal(0.0, sigma_S * sqrt_dt, size=int(tburn / dt))
    dW_S      = rng.normal(0.0, sigma_S * sqrt_dt, size=len(t))

    dW_E_burn = rng.normal(0.0, sigma_E * sqrt_dt, size=int(tburn / dt))
    dW_E      = rng.normal(0.0, sigma_E * sqrt_dt, size=len(t))

    dW_I_burn = rng.normal(0.0, sigma_I * sqrt_dt, size=int(tburn / dt))
    dW_I      = rng.normal(0.0, sigma_I * sqrt_dt, size=len(t))

    dW_P      = rng.normal(0.0, sigma_P * sqrt_dt, size=len(t))
    dW_P[:nramp_1] = 0.0

    dW_Q      = rng.normal(0.0, sigma_Q * sqrt_dt, size=len(t))
    dW_Q[:nramp_1] = 0.0

    dW_R_burn = rng.normal(0.0, sigma_R * sqrt_dt, size=int(tburn / dt))
    dW_R      = rng.normal(0.0, sigma_R * sqrt_dt, size=len(t))

    # ---------- burn-in ----------
    for i in range(len(dW_S_burn)):
        S_burn += de_fun_S(S_burn, I_burn, P_burn, 0, Lambda, beta[0], pi[0], phi[0], 1, mu) * dt + dW_S_burn[i]
        E_burn += de_fun_E(S_burn, E_burn, I_burn, P_burn, 0, beta[0], theta, epsilon, 1, mu) * dt + dW_E_burn[i]
        I_burn += de_fun_I(E_burn, I_burn, theta, gamma, 0, mu) * dt + dW_I_burn[i]
        P_burn = 0.0
        Q_burn = 0.0
        R_burn += de_fun_R(I_burn, R_burn, Q_burn, gamma, tau, mu) * dt + dW_R_burn[i]

        if S_burn < 0: S_burn = 0.0
        if E_burn < 0: E_burn = 0.0
        if I_burn < 0: I_burn = 0.0
        if R_burn < 0: R_burn = 0.0

    if E_burn < 0.1: E_burn = rng.uniform(0.1, 1.0)
    if I_burn < 0.1: I_burn = rng.uniform(0.1, 1.0)

    # ---------- allocate state ----------
    I = np.empty(len(t))

    S, E, I[0], P, Q, R = S_burn, E_burn, I_burn, P_burn, Q_burn, R_burn

    # ---------- main simulation ----------
    for i in range(len(t) - 1):
        if i < nramp_1:
            S_new = S + de_fun_S(S, I[i], P, 0,Lambda, beta[i], pi[i], phi[i], 1, mu) * dt + S*dW_S[i]
            E_new = E + de_fun_E(S, E, I[i], P, 0,beta[i], theta, epsilon, 1,mu) * dt + E*dW_E[i]
            I[i+1] = I[i] + de_fun_I(E, I[i], theta, gamma, 0.0, mu)*dt + I[i]*dW_I[i]
        else:
            S_new = S + de_fun_S(S, I[i], P, Q,Lambda, beta[i], pi[i], phi[i],epsilon_q,mu) * dt + S*dW_S[i]
            E_new = E + de_fun_E(S, E, I[i], P, Q, beta[i], theta, epsilon, epsilon_q,mu) * dt + E*dW_E[i]
            I[i+1] = I[i] + de_fun_I(E, I[i], theta, gamma, delta, mu) * dt + I[i]*dW_I[i]

        if i < nramp_1:
            P_new = 0.0
            Q_new = 0.0
        else:
            P_new = P + de_fun_P(S, I[i], P, beta[i], pi[i], phi[i], epsilon, mu) * dt + P*dW_P[i]
            Q_new = Q + de_fun_Q(Q, I[i], delta, mu, tau) * dt + Q*dW_Q[i]

        R_new = R + de_fun_R(I[i], R, Q, gamma, tau, mu) * dt

        if S_new < 0: S_new = 0.0
        if E_new < 0: E_new = rng.uniform(0,0.5)
        if I[i+1] < 0: I[i+1] = rng.uniform(0,0.5)
        if P_new < 0: P_new = rng.uniform(0,0.5)
        if Q_new < 0: Q_new = rng.uniform(0,0.5)

        if R_new < 0: R_new = 0.0

        Ro[i+1] = beta[i] * theta * ( Lambda / mu ) * (mu + phi[i] + (1-epsilon) * pi[i])/((mu+gamma)*(mu+theta)*(mu + phi[i] + pi[i]))


        S, E, P,Q, R = S_new, E_new, P_new, Q_new, R_new
   
    return (
        S, E, I[-1], P, Q, R,
        beta[-1], pi[-1], phi[-1]
    )

results = Parallel(n_jobs=NUM_THREADS, prefer="processes")(
    delayed(run_one_sim)(j)
    for j in tqdm(range(numSims), desc="Phase I simulations")
)


(
    S_last,
    E_last,
    I_last,
    P_last,
    Q_last,
    R_last,
    beta_last,
    pi_last,
    phi_last
) = zip(*results)

S_last = np.array(S_last)
E_last = np.array(E_last)
I_last = np.array(I_last)
P_last = np.array(P_last)
Q_last = np.array(Q_last)
R_last = np.array(R_last)
beta_last = np.array(beta_last)
pi_last = np.array(pi_last)
phi_last = np.array(phi_last)

# ============== PHASE II ==============================
phase2_seeds = master_rng.integers(
    low=0,
    high=2**63,
    size=numSims,
    dtype=np.int64
)

phase2_rng = np.random.default_rng(global_seed + 2)


# this will run for n_ramp2 time
t_2 = np.arange(t0,tphase_2,dt)

tbif_2 = np.zeros(numSims) # bifurcation times for phase II
                                    
beta = []

# ======== PI AND PHI MODELING ===========
pi = np.zeros(len(t_2))
phi = np.zeros(len(t_2))

# --- Vectorized π/φ decay parameters (per simulation) ---
pi_last_arr  = np.asarray(pi_last)
phi_last_arr = np.asarray(phi_last)

# decay times (days)
tdecay_pi_j = phase2_rng.uniform(150, 800, size=numSims)

# number of steps per simulation
ndecay_pi = (tdecay_pi_j / dt).astype(int) + 1

# linear decay slopes
pi1_2  = (param_pi_final  - pi_last_arr)  / tdecay_pi_j
phi1_2 = (param_phi_final - phi_last_arr) / tdecay_pi_j

# ========= BETA MODELING =========================
# suppress beta first for tsuppress_beta_2 and then ramp beta for tramp_beta_2
beta_suppression = phase2_rng.uniform(0.30,0.60,numSims)
# beta_suppression = 0
tsuppress_beta_2 = 75
tramp_beta_2 = tphase_2 - tsuppress_beta_2
n_suppress = int(tsuppress_beta_2 / dt)
t_suppress = t_2[:n_suppress]  # First n_suppress points
t_ramp_b2 = t_2[n_suppress:] - tsuppress_beta_2  # Elapsed time post-suppression (starts at 0)

# critical beta array

betabif_2_numerator = mu  * (mu + theta)  * (mu + gamma + delta) * (mu + param_phi_final + 0.2 * pi_last_arr)*(mu+tau)
betabif_2_denominator = theta*Lambda*((mu + param_phi_final)*(mu+tau)+delta*(1-epsilon_q)*(mu+param_phi_final) + (1 - epsilon)*0.2*pi_last_arr*(mu+tau))

betabif_2 = betabif_2_numerator/betabif_2_denominator
    
    


# reduce beta from end of phase 1 before ramping it up again
depressed_beta_2 = (1.0 - beta_suppression) * beta_last

# ---------- suppression slope ----------
beta_suppression_slope_2 = (
- beta_suppression * beta_last / tsuppress_beta_2
)

# ---------- ramp slopes ----------
mode_fraction = 0.25

left_slope  = (1.0 * betabif_2 - depressed_beta_2) / tramp_beta_2
right_slope = (2.0 * betabif_2 - depressed_beta_2) / tramp_beta_2 # was 1.5
mid_slope   = left_slope + mode_fraction * (right_slope - left_slope)

beta_ramp_slope_2 = phase2_rng.triangular(
    left_slope,
    mid_slope,
    right_slope,
    size=numSims
)
# shape: (numSims,)


# loop over simulations
print('\nBegin simulations Phase II \n')
def run_phase2_sim(j):
    rng = np.random.default_rng(phase2_seeds[j])

    I = np.zeros(len(t_2))
    
    pi  = np.zeros(len(t_2))
    phi = np.zeros(len(t_2))
    Reff = np.zeros(len(t_2))
    Ro = np.zeros(len(t_2))
    beta = np.zeros(len(t_2))

    S = S_last[j]
    E = E_last[j]
    P = P_last[j]
    Q = Q_last[j]
    R = R_last[j]
    I[0] = I_last[j]
    pi0_2  = pi_last[j]
    phi0_2 = phi_last[j]
    
    b0 = beta_last[j]
    b0_d = depressed_beta_2[j]
    beta_suppress = b0 + t_suppress * beta_suppression_slope_2[j]
    beta_ramp = b0_d + t_ramp_b2 * beta_ramp_slope_2[j]
    beta[:n_suppress] = beta_suppress
    beta[n_suppress:] = beta_ramp  # Hold at final after decay

    n = min(ndecay_pi[j], len(t_2))
    t_j = np.arange(n) * dt
    pi[:n] = pi0_2 + pi1_2[j] * t_j
    phi[:n] = phi0_2 + phi1_2[j] * t_j
    pi[n:] = param_pi_final[j]
    phi[n:] = param_phi_final[j]

    # ==== NOISE ====================
    
    sigma_S = np.random.triangular(0, 0.05, 0.10)                                    
    sigma_I = np.random.triangular(0, 0.05, 0.10)      
    sigma_E = np.random.triangular(0, 0.05, 0.10)      
    sigma_P = np.random.triangular(0, 0.05, 0.10)     
    sigma_Q = np.random.triangular(0, 0.05, 0.10)     
    sigma_R = np.random.triangular(0, 0.05, 0.10)
    
    # calculate initial value of Reff before entering simulation
    Reff[0] = beta[0]*theta*(S + (1-epsilon)*P) /((mu+gamma)*(mu+theta))
    Ro[0] = beta[0] * theta * ( Lambda / mu ) * (mu + phi[0] + (1-epsilon) * pi[0] + (1-epsilon_q)*delta*(mu+phi[0])/(mu+tau))/((mu+gamma+delta)*(mu+theta)*(mu + phi[0] + pi[0]))


    dW_S = rng.normal(loc=0, scale=sigma_S*np.sqrt(dt), size = len(t_2))
    dW_E = rng.normal(loc=0, scale=sigma_E*np.sqrt(dt), size = len(t_2))
    dW_I = rng.normal(loc=0, scale=sigma_I*np.sqrt(dt), size = len(t_2))
    dW_P = rng.normal(loc=0, scale=sigma_P*np.sqrt(dt), size = len(t_2))
    dW_Q = rng.normal(loc=0, scale=sigma_Q*np.sqrt(dt), size = len(t_2))
    dW_R = rng.normal(loc=0, scale=sigma_R*np.sqrt(dt), size = len(t_2))

# ================ Run simulation ===================
    for i in range(len(t_2)-1):
        S_new= S + de_fun_S(S,I[i],P,Q,Lambda,beta[i],pi[i],phi[i],epsilon_q,mu)*dt + S*dW_S[i]
        E_new = E + de_fun_E(S,E,I[i],P,Q,beta[i],theta,epsilon,epsilon_q,mu)*dt + E*dW_E[i]
        I[i+1] = I[i] + de_fun_I(E,I[i],theta,gamma,delta,mu)*dt + I[i]*dW_I[i]
        P_new = P + de_fun_P(S,I[i],P,beta[i],pi[i],phi[i],epsilon,mu)*dt + P*dW_P[i]
        Q_new = Q + de_fun_Q(Q,I[i],delta,mu,tau)*dt + Q*dW_Q[i]
        R_new = R + de_fun_R(I[i],R,Q,gamma,tau,mu)*dt
        
        # make sure that state variable remains >= 0
        if S_new < 0:                                                                  
            S_new = 0
        if E_new < 0.1:
            E_new = rng.uniform(0.1,0.2)
        if I[i+1] < 0.1:
            I[i+1] = rng.uniform(0.1,0.2)
        if P_new < 0:
            P_new = rng.uniform(0.1,0.5)
        if Q_new < 0:
            Q_new = rng.uniform(0.1,0.5)
        if R_new < 0:
            R_new = rng.uniform(0.1,0.5)

        # calculate Reff for each step
        Reff[i+1] = beta[i]*theta*(S_new + (1-epsilon)*P_new) /((mu+gamma)*(mu+theta))
        Ro[i+1] = beta[i] * theta * ( Lambda / mu ) * (mu + phi[i] + (1-epsilon) * pi[i] + (1-epsilon_q)*delta*(mu+phi[i])/(mu+tau))/((mu+gamma+delta)*(mu+theta)*(mu + phi[i] + pi[i]))
        S, E, P, Q, R = S_new, E_new, P_new, Q_new, R_new

    if np.any(Ro > 1.0):
        idx = np.where(Ro > 1.0)[0][0]
        tbif = t_2[idx]
        label = 1
    else:
        tbif = tphase_2
        label = 0

    stride = int(dt2 / dt)
    I_ds = I[::stride]

    return I_ds, tbif, label

results = Parallel(n_jobs=NUM_THREADS, prefer="processes")(
    delayed(run_phase2_sim)(j)
    for j in tqdm(range(numSims), desc="Phase II simulations")
)

I_list, tbif_2, labels = zip(*results)

stride = int(dt2 / dt)

I_all = np.vstack(I_list)     # shape: (numSims, n_time)
t_ds = t_2[::stride]
tbif_2 = np.array(tbif_2)
labels = np.asarray(labels)

df_traj = pd.DataFrame(
    I_all,
    index=pd.Index(np.arange(1, numSims + 1), name="tsid"),
    columns=t_ds
).stack().to_frame("I")

df_traj.index.set_names(["tsid", "Time"], inplace=True)

label = pd.DataFrame({
    "sequence_ID": np.arange(sim_index+1, sim_index+1+numSims),
    "class_value": labels
})

del I, beta
del beta_intercept, right_intercept, mid_intercept, beta_target
gc.collect()   
#Concatenate(merge) DataFrame from each j 

# Compute EWS, variance and lag-1 AC for each simulation
#---------------------

# Filter time-series to have time-spacing dt2


# set up a list to store output dataframes from ews_compute- we will concatenate them at the end
appended_ews = []

# loop through realisation number
print('\nBegin EWS computation\n')
appended_ews = Parallel(n_jobs=NUM_THREADS)(
    delayed(process_sim)(i, df_traj, tbif_2, span, rw)
    for i in trange(numSims)
)


# Concatenate EWS DataFrames
df_ews = pd.concat(appended_ews).reset_index().set_index(['tsid','Variable','Time'])

if not os.path.exists('../training_data/AddNoise/output_sims_batch{}'.format(count)):
    os.makedirs('../training_data/AddNoise/output_sims_batch{}'.format(count)) 

if not os.path.exists('../training_data/AddNoise/resids{}'.format(count)):
    os.makedirs('../training_data/AddNoise/resids{}'.format(count)) 

print('generating labels and tseries csvs')

# Flatten index and sort
df_ews_flat = (
    df_ews
    .reset_index()                     # tsid, Variable, Time become columns
    .sort_values(["tsid", "Variable", "Time"], kind="mergesort")
)

df_ews_flat = df_ews_flat[
    ["tsid", "Variable", "Time", "state", "residuals"]
]

# Group by (tsid, Variable)
groups = {
    (tsid, var): df
    for (tsid, var), df in df_ews_flat.groupby(
        ["tsid", "Variable"], sort=False
    )
}

num_threads = 4
with ThreadPoolExecutor(max_workers=NUM_THREADS) as executor:
    futures = [
        executor.submit(save_csv, i, groups, count, sim_index)
        for i in range(1, numSims+1)
    ]
    for _ in tqdm(as_completed(futures), total=len(futures), desc="Saving CSVs"):
        pass

# ---- NULL residuals (truncated 28 days before tbif_2) ----
print('\nBegin null EWS computation\n')
appended_null_ews = Parallel(n_jobs=NUM_THREADS)(
    delayed(process_null_sim)(i, df_traj, tbif_2, span, rw)
    for i in trange(numSims)
)
df_null_ews = pd.concat(appended_null_ews).reset_index().set_index(['tsid', 'Variable', 'Time'])
df_null_ews_flat = (
    df_null_ews.reset_index()
    .sort_values(["tsid", "Variable", "Time"], kind="mergesort")
)[["tsid", "Variable", "Time", "state", "residuals"]]

null_groups = {
    (tsid, var): df
    for (tsid, var), df in df_null_ews_flat.groupby(["tsid", "Variable"], sort=False)
}
with ThreadPoolExecutor(max_workers=NUM_THREADS) as executor:
    futures = [
        executor.submit(save_null_csv, i, null_groups, count, null_offset)
        for i in range(1, numSims + 1)
    ]
    for _ in tqdm(as_completed(futures), total=len(futures), desc="Saving null CSVs"):
        pass

print('generating labels.csv')
if not os.path.exists('../training_data/AddNoise/output_labels'):
    os.makedirs('../training_data/AddNoise/output_labels')
    
#label_indv
filepath = '../training_data/AddNoise/output_labels/label_{}.csv'.format(count)
label.to_csv(filepath,
            header=False, index=False) 

null_label = pd.DataFrame({
    "sequence_ID": np.arange(null_offset + 1+ sim_index, null_offset + 1 + sim_index + numSims),
    "class_value": np.zeros(numSims, dtype=int)
})
null_label.to_csv(
    '../training_data/AddNoise/output_labels/label_null_{}.csv'.format(count),
    header=False, index=False
)
pd.DataFrame(tbif_2).to_csv('../training_data/AddNoise/output_labels/bifurcation_points_batch{}.csv'.format(count), header=False, index=False)
